// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionOrders.API.Models.Data;

#nullable disable

namespace SolutionOrders.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604115355_AddUserLogin")]
    partial class AddUserLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionOrders.API.Models.AppUser", b =>
                {
                    b.Property<int>("IdAppUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAppUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAppUser");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            IdAppUser = 1,
                            Email = "admin@test.pl",
                            IsActive = true,
                            Name = "Administrator",
                            Password = "admin",
                            Role = "Admin"
                        },
                        new
                        {
                            IdAppUser = 2,
                            Email = "user@test.pl",
                            IsActive = true,
                            Name = "Użytkownik",
                            Password = "user",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Author", b =>
                {
                    b.Property<int>("IdAuthor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuthor"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAuthor");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            IdAuthor = 1,
                            FirstName = "Andrzej",
                            IsActive = true,
                            LastName = "Sapkowski"
                        },
                        new
                        {
                            IdAuthor = 2,
                            FirstName = "J.K.",
                            IsActive = true,
                            LastName = "Rowling"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Book", b =>
                {
                    b.Property<int>("IdBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBook"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAuthor")
                        .HasColumnType("int");

                    b.Property<int?>("IdPublisher")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBook");

                    b.HasIndex("IdAuthor");

                    b.HasIndex("IdPublisher");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            IdBook = 1,
                            Description = "Przygody Geralta z Rivii",
                            IdAuthor = 1,
                            IdPublisher = 1,
                            IsActive = true,
                            Language = "Polski",
                            Pages = 332,
                            Price = 39.99m,
                            Title = "Wiedźmin: Ostatnie życzenie"
                        },
                        new
                        {
                            IdBook = 2,
                            Description = "Pierwsza część serii Harry Potter",
                            IdAuthor = 2,
                            IdPublisher = 1,
                            IsActive = true,
                            Language = "Polski",
                            Pages = 320,
                            Price = 49.99m,
                            Title = "Harry Potter i Kamień Filozoficzny"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.BookBookCategory", b =>
                {
                    b.Property<int>("IdBook")
                        .HasColumnType("int");

                    b.Property<int>("IdBookCategory")
                        .HasColumnType("int");

                    b.HasKey("IdBook", "IdBookCategory");

                    b.HasIndex("IdBookCategory");

                    b.ToTable("BookBookCategories");

                    b.HasData(
                        new
                        {
                            IdBook = 1,
                            IdBookCategory = 1
                        },
                        new
                        {
                            IdBook = 2,
                            IdBookCategory = 1
                        },
                        new
                        {
                            IdBook = 2,
                            IdBookCategory = 2
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.BookCategory", b =>
                {
                    b.Property<int>("IdBookCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBookCategory"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBookCategory");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            IdBookCategory = 1,
                            IsActive = true,
                            Name = "Fantasy"
                        },
                        new
                        {
                            IdBookCategory = 2,
                            IsActive = true,
                            Name = "Przygodowe"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.BookOrder", b =>
                {
                    b.Property<int>("IdBookOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBookOrder"));

                    b.Property<int>("IdAppUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdBookOrder");

                    b.HasIndex("IdAppUser");

                    b.ToTable("BookOrders");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.BookOrderItem", b =>
                {
                    b.Property<int>("IdBookOrderItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBookOrderItem"));

                    b.Property<int>("IdBook")
                        .HasColumnType("int");

                    b.Property<int>("IdBookOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdBookOrderItem");

                    b.HasIndex("IdBook");

                    b.HasIndex("IdBookOrder");

                    b.ToTable("BookOrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            Description = "Urządzenia elektroniczne",
                            IsActive = true,
                            Name = "Elektronika"
                        },
                        new
                        {
                            IdCategory = 2,
                            Description = "Produkty spożywcze",
                            IsActive = true,
                            Name = "Żywność"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Address = "ul. Główna 1, Warszawa",
                            IsActive = true,
                            Name = "Jan Kowalski",
                            PhoneNumber = "500-100-200"
                        },
                        new
                        {
                            IdClient = 2,
                            Address = "ul. Kwiatowa 5, Kraków",
                            IsActive = true,
                            Name = "Anna Nowak",
                            PhoneNumber = "600-200-300"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnitOfMeasurement")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdItem");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdUnitOfMeasurement");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            IdItem = 1,
                            Code = "LAP001",
                            Description = "Laptop Dell Inspiron 15",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Laptop Dell",
                            Price = 3500m,
                            Quantity = 10m
                        },
                        new
                        {
                            IdItem = 2,
                            Code = "MON001",
                            Description = "Monitor 24 cale",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Monitor Samsung",
                            Price = 800m,
                            Quantity = 15m
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<DateTime?>("DataOrder")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdWorker")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdWorker");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.OrderItem", b =>
                {
                    b.Property<int>("IdOrderItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrderItem"));

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdOrderItem");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdOrder");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Publisher", b =>
                {
                    b.Property<int>("IdPublisher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPublisher"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPublisher");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            IdPublisher = 1,
                            IsActive = true,
                            Name = "SuperNOWA"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReview"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdBook")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("IdReview");

                    b.HasIndex("IdBook");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            IdReview = 1,
                            Content = "Bardzo dobra książka, świetny klimat.",
                            IdBook = 1,
                            IsActive = true,
                            Rating = 5
                        },
                        new
                        {
                            IdReview = 2,
                            Content = "Ciekawa historia i dobrze napisane postacie.",
                            IdBook = 2,
                            IsActive = true,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("IdUnitOfMeasurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnitOfMeasurement"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUnitOfMeasurement");

                    b.ToTable("UnitOfMeasurements");

                    b.HasData(
                        new
                        {
                            IdUnitOfMeasurement = 1,
                            Description = "Sztuki",
                            IsActive = true,
                            Name = "szt"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 2,
                            Description = "Kilogramy",
                            IsActive = true,
                            Name = "kg"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 3,
                            Description = "Litry",
                            IsActive = true,
                            Name = "l"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Worker", b =>
                {
                    b.Property<int>("IdWorker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWorker"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdWorker");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            IdWorker = 1,
                            FirstName = "Piotr",
                            IsActive = true,
                            LastName = "Kowalczyk",
                            Login = "pkowalczyk"
                        },
                        new
                        {
                            IdWorker = 2,
                            FirstName = "Maria",
                            IsActive = true,
                            LastName = "Wiśniewska",
                            Login = "mwisnieska"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Book", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("IdAuthor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionOrders.API.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("IdPublisher");

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.BookBookCategory", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Book", "Book")
                        .WithMany("BookBookCategories")
                        .HasForeignKey("IdBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionOrders.API.Models.BookCategory", "BookCategory")
                        .WithMany("BookBookCategories")
                        .HasForeignKey("IdBookCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookCategory");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.BookOrder", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.AppUser", "AppUser")
                        .WithMany("BookOrders")
                        .HasForeignKey("IdAppUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.BookOrderItem", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Book", "Book")
                        .WithMany("BookOrderItems")
                        .HasForeignKey("IdBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionOrders.API.Models.BookOrder", "BookOrder")
                        .WithMany("BookOrderItems")
                        .HasForeignKey("IdBookOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookOrder");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Item", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrders.API.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Items")
                        .HasForeignKey("IdUnitOfMeasurement")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Order", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolutionOrders.API.Models.Worker", "Worker")
                        .WithMany("Orders")
                        .HasForeignKey("IdWorker")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.OrderItem", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrders.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Review", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("IdBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.AppUser", b =>
                {
                    b.Navigation("BookOrders");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Book", b =>
                {
                    b.Navigation("BookBookCategories");

                    b.Navigation("BookOrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.BookCategory", b =>
                {
                    b.Navigation("BookBookCategories");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.BookOrder", b =>
                {
                    b.Navigation("BookOrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Item", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Worker", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
